### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by AndreiZaycev** [Volodya-Petrov/arp-spoofing-utility#3]
Здравствуйте! Я запускаю ваш арбсбуфенг и чето не робит, я может чето не так делаю? Я вот скачал вроде поставил но чето не работает может быть проблема у меня я сижу на windus 15 у миня еще dota 2 запущена это влияет как-то не знаете? Я также включил видео называется arpspof kil ur internet wibe phonk чето не похоже на гайд вот ссылка https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley

**Comment by AndreiZaycev** [comment]
![image](https://user-images.githubusercontent.com/71140884/204531405-67c3f36f-99cb-443a-8cf4-9b8c425be4b6.png)

**Comment by Volodya-Petrov** [comment]
Взяли в работу

**Comment by Volodya-Petrov** [comment]
Пофикшен
